### ISSUE TITLE
Нет финального экрана

### ISSUE THREAD

**Issue by YakovL** [vivilor/308-02#10]
см. картинку «308-02 final»: когда всё задание выполнено правильно, камера как бы сдвигается вправо, обгоняя движение речки и догоняя уплывшие бумажки, и показывает такой стоп-кадр (точнее, лучше, чтобы все элементы слегка пошевеливались, такая живая фотография)

**Comment by YakovL** [comment]
Это самая важная проблема на данный момент

**Comment by YakovL** [comment]
PS увидел, что https://github.com/vivilor/308-02/issues/7 было закрыто, но у меня ни в Хроме, ни в Вивальди не появляется

**Comment by vivilor** [comment]
Теперь точно стоит закрыть, подрагивание картинок (а это то, что осталось) другой Issue
