### ISSUE TITLE
Сделать анимацию "движения камеры" для попадания на финальный экран

### ISSUE THREAD

**Issue by YakovL** [vivilor/308-02#12]
Сейчас при переходе на финальный экран речка продолжает двигаться так же, как во время 2 шага, поэтому нет ощущения, что камера догоняет уплывшие клетки, а ощущение, что они просто возвращаются обратно. Если же река во время движения тоже будет уходить налево, будет движение камеры

**Comment by vivilor** [comment]
Готово. Теперь статичные ярылки плывут вместе с речкой
